### ISSUE TITLE
test/prod compile output paths for project module overlap

### ISSUE THREAD

**Issue by gbasler** [mpeltonen/sbt-idea#200]
This leads to the following error when enabling the new External Build:

```
scala: Output path C:\code\analytics-caliper\project\target\scala_2.9.2 is shared between: Module 'analytics-build' production, Module 'analytics-build' tests
Currently external Scala compiler prohibits output path sharing.
Either disable the external build mode or configure separated output paths.
TIP: you can use Project Artifacts to combine compiled classes.
```

Under the project settings for that module

```
Output path = C:\code\analytics-caliper\project\target\scala_2.9.2
Test output path = C:\code\analytics-caliper\project\target\scala_2.9.2
```

Workaround is to not create an IntelliJ module for the build with `gen-idea no-sbt-build-module`, or to edit the configuration manually to change the test output path to `C:\code\analytics-caliper\project\target\scala_2.9.2-test`

Tested with sbt-idea 1.2.0.

**Comment by jm-g** [comment]
I have a similar (the same?) problem using a multi module project:

scala: Output path master/project/target/scala_2.9.2 is shared between: Module 'commons-domain-model-build' production, Module 'commons-util-build' production, Module 'database-access-build' production, Module, Module 'nlp-build' production, Module 'rest-service-build' production, Module 'commons-domain-model-build' tests, Module 'commons-util-build' tests, Module 'database-access-build' tests, Module 'nlp-build' tests, Module 'rest-service-build' tests
Currently external Scala compiler prohibits output path sharing.
Either disable the external build mode or configure separated output paths.
TIP: you can use Project Artifacts to combine compiled classes.

**Comment by mpeltonen** [comment]
Should be fixed in 1.3.0-SNAPSHOT (for sbt 0.12)

**Comment by jm-g** [comment]
Thanks, for fixing it. Do you have a plan when you'll release 1.3.0?

**Comment by mpeltonen** [comment]
Well, I was hoping to get this: https://github.com/jberkel/android-plugin/issues/147 fixed in android plugin first, as 1.3.0-SNAPSHOT includes some android support (#191) which currently relies on forked version of the android plugin. 

But if that seems to take long, then I'll probably just cut a release and just not support the android stuff officially. Hopefully within weeks instead of months :)

**Comment by jm-g** [comment]
Well, I was too optimistic. It isn't fixed for me. I still get the following error: scala:

 Output path /Users/jgaillourdet/Repos/master/project/target/scala_2.9.2/classes is shared between: Module 'commons-domain-model-build' production, Module 'commons-util-build' production, Module 'database-access-build' production, Module 'nlp-build' production, Module 'rest-service-build' production
Output path /Users/jgaillourdet/Repos/master/project/target/scala_2.9.2/test-classes is shared between: Module 'commons-domain-model-build' tests, Module 'commons-util-build' tests, Module 'database-access-build' tests, Module 'nlp-build' tests, Module 'rest-service-build' tests
Currently external Scala compiler prohibits output path sharing.
Either disable the external build mode or configure separated output paths.
TIP: you can use Project Artifacts to combine compiled classes

This is with 1.3.0-SNAPSHOT of course.

**Comment by mpeltonen** [comment]
Hmm, this looks interesting. What kind of multiproject structure/hierarchy you have? You seem to have multiple project definition (build) modules?

Or do you import multiple sbt projects as separate Idea modules into same Idea workspace?

**Comment by jm-g** [comment]
Yey, I am using a multi-project setup. I'd like to combine internal projects into workspaces in order to be able to edit multiple projects at once in intelij. To reproduce my aforementioned problem clone the following repo: https://github.com/jm-g/sbt-example.git and cd into projb, start sbt gen-idea, and open the project in Intellij. Then try to make projb. You should get a similar compiler error to the one posted before.

**Comment by mpeltonen** [comment]
The sample projects don't have any dependencies to each other in build definition, and projb does not compile even in sbt, so are you missing a dependency definition from projb?

**Comment by jm-g** [comment]
Sorry, I forgot to add two files.These are pushed now and I've checked that I can reproduce it in a fresh clone.

**Comment by mpeltonen** [comment]
Thanks for the sample, it helped! Try if the latest snapshot now works for you.

**Comment by haitaoyao** [comment]
@mpeltonen  Can you build a 1.3.0-SNAPSHOT based on sbt-0.11.3 ? I got the same issue, but my project is still on sbt 0.11.3. 
Thanks.

**Comment by mpeltonen** [comment]
@haitaoyao: Done!

**Comment by haitaoyao** [comment]
Thanks. It works for me. Never get the error again.

**Comment by ostewart** [comment]
Fix works on my project in 1.3.0-SNAPSHOT and sbt 0.12.2.  Thanks!!

**Comment by ForNeVeR** [comment]
I can confirm that fix works with sbt 0.12.1 and sbt-idea 1.3.0-SNAPSHOT.

**Comment by doxxx** [comment]
I'm still getting this with sbt 0.12.1 and sbt-idea 1.3.0. If I use `gen-idea no-sbt-build-module`, the auto make succeeds.

```
scala: Output path C:\dev\spatula\project\target\scala_2.9.2 is shared between: Module 'spatula-build' production, Module 'spatula-build' tests
Currently external Scala compiler prohibits output path sharing.
Either disable the external build mode or configure separate output paths.
TIP: you can use Project Artifacts to combine compiled classes.
```
